"""
Tests for the shareable HTML fleet health record (theta/agent/fleetreport.py)
and its two CLI entry points (theta demo --html, theta fleet-scan --html).

Same honesty bar as test_demo.py: the scope paragraph must always render,
ground-truth badges only appear when the caller provides them, and the
bundled-incident report must stay identifier-clean.
"""

import json

from typer.testing import CliRunner

from theta.agent.demo import load_fixture, report_input, run_replay
from theta.agent.fleetreport import ReportInput, ReportRow, render_fleet_report



def _demo_html() -> str:
    fixture = load_fixture()
    res = run_replay(fixture)
    return render_fleet_report(report_input(fixture, res))


def test_demo_report_contains_flags_and_receipt():
    html = _demo_html()
    # All three flagged units appear, with the confirmation badges.
    for gpu in ("node-05:7", "node-03:6", "node-05:2"):
        assert gpu in html
    # The two confirmations carry DISTINCT badges (never merged into one
    # claim); each unit renders in both the flagged table and the
    # full-standings table.
    assert html.count("RMA-replaced") == 2
    assert html.count("re-confirmed") == 2
    assert "unconfirmed" in html
    # Branding + install path travel with the artifact.
    assert "Generated by" in html and "runtheta" in html


def test_demo_report_scope_always_renders():
    html = _demo_html()
    assert "does not" in html and "predict failure dates" in html
    assert "independently confirmed, two different ways" in html


def test_demo_report_is_pseudonymous():
    # Every GPU named in the shareable record is a node-NN:D pseudonym; no raw
    # hostnames of any shape appear. (The against-the-raw-export scan lives
    # with the private derivation script.)
    import re
    html = _demo_html()
    gpus = re.findall(r'<td class="mono">([^<]+)</td>', html)
    assert gpus and all(re.fullmatch(r"node-\d{2}:\d", g) for g in gpus)
    assert "de-identified" in html


def test_report_without_ground_truth_shows_no_badges():
    rows = [ReportRow(gpu=f"n1:{i}", node="n1", temp_c=None, power_w=400.0,
                      rtheta=0.30, z=0.5) for i in range(8)]
    rows[0].z = 9.0
    html = render_fleet_report(ReportInput(
        title="t", fleet_desc="d", rows=rows, ref_power=400.0,
        temp_threshold_c=None, scope_note="scope text here",
    ))
    assert "RMA" not in html
    assert "scope text here" in html
    assert "CRITICAL" in html  # z=9 crosses the critical threshold


def test_cli_demo_html_writes_file(tmp_path):
    from theta.cli import app

    out = tmp_path / "record.html"
    res = CliRunner().invoke(app, ["demo", "--html", str(out)])
    assert res.exit_code == 0, res.output
    text = out.read_text()
    assert text.startswith("<!doctype html>")
    assert "node-05:7" in text


def test_cli_fleet_scan_html_writes_file(tmp_path):
    from theta.cli import app

    # Minimal 2-node export in the results.json shape fleet-scan accepts.
    export = {"steady_bad": {
        f"{node}:{i}": {"r_mean": 0.055 + (0.03 if (node, i) == ("a", 7) else 0.0004 * i),
                        "P_mean": 650.0}
        for node in ("a", "b") for i in range(8)
    }}
    src = tmp_path / "export.json"
    src.write_text(json.dumps(export))
    out = tmp_path / "scan.html"

    res = CliRunner().invoke(app, ["fleet-scan", str(src), "--html", str(out)])
    assert res.exit_code == 0, res.output
    text = out.read_text()
    assert text.startswith("<!doctype html>")
    assert "a:7" in text                    # the planted outlier is in the report
    assert "condition, not failure dates" in text
